name: Release vscode-lexical

on:
  push:
    tags:
      - v*

jobs:
  publish-vscode:
    runs-on: ubuntu-latest
    name: Build and publish vscode-lexical to official VSCode marketplace
    env:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Publish extension
        run: npm run vsce:publish

  publish-openvsx:
    runs-on: ubuntu-latest
    name: Build and publish vscode-lexical to Open VSX marketplace
    env:
      OVSX_PAT: ${{ secrets.OVSX_PAT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Publish extension
        run: npm run ovsx:publish ${{ env.OVSX_PAT }}

  github-release:
    runs-on: ubuntu-latest
    name: Create Github Release
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Package vscode-lexical
        run: npm run vsce:package --out vscode-lexical.vsix

      - run: cp vscode-lexical.vsix vscode-lexical-${{ github.ref_name }}.vsix

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: vscode-lexical*.vsix
          makeLatest: true
          allowUpdates: true
          body: >
            See the
            [changelog](https://github.com/lexical-lsp/vscode-lexical/blob/main/CHANGELOG.md)
            for the full release notes.
